### ISSUE TITLE
Starting

### ISSUE THREAD

**Issue by ps-arndwestermann** [NanoVash/SnakeNN#3]
Hay ho, maybe i'm just to dumb for this, but how do i start this game?^^

**Comment by NatanSkl** [comment]
Hey! Check the releases section for a downloadable jar you can execute. To further understand how to play and what different things do, refer to the README.md file for a detailed explanation.

**Comment by ps-arndwestermann** [comment]
Thank you, i didn't see this in the Readme section. ^^"
